core/urls.py
from django.contrib import admin
from django.urls import path , include

app_name = 'mysite'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mysite/",include('mysite.urls'))
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

app_name = 'mysite'

urlpatterns = [
    path("index/",views.home,name='home'),
    path("detail/",views.detail,name='detail'),
]

mysite/models.py
from django.db import models

# Create your models here.

mysite/views.py
from django.shortcuts import render
from django.http import request
# Create your views here.
def home(request):
    return render(request,'mysite/home.html')

def detail(request):
    return render(request,'mysite/detail.html')

mysite/templates/mysite/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{%  static 'mysite/css/bootstrap.min.css'%}">
    <script src="{% static 'mysite/js/bootstrap.min.js' %}"></script>
    <title>{%block title%}  {%endblock%}</title>
    
</head>
<body>
    
    {% include "mysite/header.html" %}
  {% block content %}
  
  
  {%endblock%}
  
  
</body>
{% include "mysite/footer.html" %}
</html>

mysite/templates/mysite/detail.html
{%extends "mysite/base.html"%}

{%block title%}
Mysite | Detail
{%endblock%}



{%block content%}
<h1>This is Detail page</h1>

    {%endblock%}
   

mysite/templates/mysite/footer.html
<footer class="bg-dark text-white py-3" style="position: fixed; bottom: 0; width: 100%;">
    <div class="container">
      <!-- Footer content -->
      <p>&copy; 2023 Your Website. All rights reserved.</p>
      <!-- Social media links -->
      {% comment %} <ul class="list-inline text-center">
        <li class="list-inline-item"><a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
        <li class="list-inline-item"><a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a></li>
      </ul> {% endcomment %}
    </div>
  </footer>
  
  
  

mysite/templates/mysite/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <img src="" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mysite:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mysite:detail' %}">Detail</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  

mysite/templates/mysite/home.html
{%extends "mysite/base.html"%}

{%block title%}
Mysite | Home
{%endblock%}



{%block content%}
    <h1>This is Home page</h1>
    {%endblock%}